" Neon Doll: hot pink neon on midnight plum.
" Generated by tools/build-vim.py; edit that, not this.
" Follows 'background'. Exact colors with 'termguicolors', the 16
" terminal colors (and so the terminal's Neon Doll scheme) without.

hi clear
if exists('syntax_on') | syntax reset | endif
let g:colors_name = 'neon-doll'

if &background ==# 'light'
  hi Normal guifg=#1a1522 guibg=#f7f4fa ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi NonText guifg=#8d84a0 guibg=NONE ctermfg=8 ctermbg=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#d6cce2 guibg=NONE ctermfg=0 ctermbg=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#8d84a0 guibg=NONE ctermfg=8 ctermbg=NONE gui=NONE cterm=NONE
  hi Whitespace guifg=#d6cce2 guibg=NONE ctermfg=0 ctermbg=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#8d84a0 guibg=NONE ctermfg=8 ctermbg=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#c8006a guibg=#f0ebf8 ctermfg=13 ctermbg=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#f0ebf8 ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#f0ebf8 ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=#f0ebf8 ctermfg=NONE ctermbg=0 gui=NONE cterm=NONE
  hi SignColumn guifg=#5f5670 guibg=NONE ctermfg=8 ctermbg=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#8d84a0 guibg=NONE ctermfg=8 ctermbg=NONE gui=NONE cterm=NONE
  hi Folded guifg=#5f5670 guibg=#f0ebf8 ctermfg=8 ctermbg=NONE gui=italic cterm=italic
  hi WinSeparator guifg=#d6cce2 guibg=NONE ctermfg=0 ctermbg=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#d6cce2 guibg=NONE ctermfg=0 ctermbg=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#1a1522 guibg=#ede7f3 ctermfg=NONE ctermbg=0 gui=NONE cterm=NONE
  hi StatusLineNC guifg=#5f5670 guibg=#f7f4fa ctermfg=8 ctermbg=NONE gui=NONE cterm=NONE
  hi StatusLineTerm guifg=#1a1522 guibg=#ede7f3 ctermfg=NONE ctermbg=0 gui=NONE cterm=NONE
  hi StatusLineTermNC guifg=#5f5670 guibg=#f7f4fa ctermfg=8 ctermbg=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#5f5670 guibg=#ede7f3 ctermfg=8 ctermbg=0 gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=#f7f4fa ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#c8006a guibg=#f7f4fa ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#1a1522 guibg=#ede7f3 ctermfg=NONE ctermbg=0 gui=NONE cterm=NONE
  hi PmenuSel guifg=#c8006a guibg=#f3e0ee ctermfg=0 ctermbg=5 gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#ede7f3 ctermfg=NONE ctermbg=0 gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#8d84a0 ctermfg=NONE ctermbg=8 gui=NONE cterm=NONE
  hi WildMenu guifg=#c8006a guibg=#f3e0ee ctermfg=0 ctermbg=5 gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#efc8e0 ctermfg=NONE ctermbg=0 gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#efc8e0 ctermfg=NONE ctermbg=0 gui=NONE cterm=NONE
  hi Search guifg=#f7f4fa guibg=#6a3fd0 ctermfg=0 ctermbg=5 gui=NONE cterm=NONE
  hi CurSearch guifg=#f7f4fa guibg=#c8006a ctermfg=0 ctermbg=13 gui=NONE cterm=NONE
  hi IncSearch guifg=#f7f4fa guibg=#c8006a ctermfg=0 ctermbg=13 gui=NONE cterm=NONE
  hi MatchParen guifg=#c8006a guibg=#f3e0ee ctermfg=5 ctermbg=NONE gui=underline cterm=underline
  hi QuickFixLine guifg=NONE guibg=#f3e0ee ctermfg=NONE ctermbg=0 gui=NONE cterm=NONE
  hi Title guifg=#6a3fd0 guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi Directory guifg=#6a3fd0 guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi Question guifg=#6a3fd0 guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#6a3fd0 guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#5f5670 guibg=NONE ctermfg=8 ctermbg=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#c4312a guibg=NONE ctermfg=1 ctermbg=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#8a6100 guibg=NONE ctermfg=3 ctermbg=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#f7f4fa guibg=#c8006a ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi lCursor guifg=#f7f4fa guibg=#c8006a ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=NONE guibg=NONE ctermfg=1 ctermbg=NONE gui=undercurl cterm=underline guisp=#c4312a
  hi SpellCap guifg=NONE guibg=NONE ctermfg=3 ctermbg=NONE gui=undercurl cterm=underline guisp=#8a6100
  hi SpellRare guifg=NONE guibg=NONE ctermfg=5 ctermbg=NONE gui=undercurl cterm=underline guisp=#6a3fd0
  hi SpellLocal guifg=NONE guibg=NONE ctermfg=6 ctermbg=NONE gui=undercurl cterm=underline guisp=#5f5670
  hi DiffAdd guifg=#1f7a33 guibg=#e8ebec ctermfg=2 ctermbg=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=#c4312a guibg=#f3e6eb ctermfg=1 ctermbg=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#efeae8 ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi DiffText guifg=#8a6100 guibg=#efeae8 ctermfg=3 ctermbg=NONE gui=underline cterm=underline
  hi Comment guifg=#5f5670 guibg=NONE ctermfg=8 ctermbg=NONE gui=italic cterm=italic
  hi Constant guifg=#6a3fd0 guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi String guifg=#8a6100 guibg=NONE ctermfg=3 ctermbg=NONE gui=NONE cterm=NONE
  hi Character guifg=#8a6100 guibg=NONE ctermfg=3 ctermbg=NONE gui=NONE cterm=NONE
  hi Number guifg=#6a3fd0 guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi Boolean guifg=#6a3fd0 guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi Float guifg=#6a3fd0 guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#1a1522 guibg=NONE ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi Function guifg=#1a1522 guibg=NONE ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#c8006a guibg=NONE ctermfg=13 ctermbg=NONE gui=NONE cterm=NONE
  hi Operator guifg=#1a1522 guibg=NONE ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#c8006a guibg=NONE ctermfg=13 ctermbg=NONE gui=NONE cterm=NONE
  hi Type guifg=#6a3fd0 guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi Special guifg=#6a3fd0 guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#1a1522 guibg=NONE ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#6a3fd0 guibg=NONE ctermfg=5 ctermbg=NONE gui=underline cterm=underline
  hi Ignore guifg=#8d84a0 guibg=NONE ctermfg=8 ctermbg=NONE gui=NONE cterm=NONE
  hi Error guifg=#c4312a guibg=#f3e6eb ctermfg=1 ctermbg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#8a6100 guibg=NONE ctermfg=3 ctermbg=NONE gui=italic cterm=italic
  hi Added guifg=#1f7a33 guibg=NONE ctermfg=2 ctermbg=NONE gui=NONE cterm=NONE
  hi Removed guifg=#c4312a guibg=NONE ctermfg=1 ctermbg=NONE gui=NONE cterm=NONE
  hi Changed guifg=#8a6100 guibg=NONE ctermfg=3 ctermbg=NONE gui=NONE cterm=NONE
else
  hi Normal guifg=#ebe6f0 guibg=#0f0d14 ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi NonText guifg=#6f6880 guibg=NONE ctermfg=8 ctermbg=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#2a2438 guibg=NONE ctermfg=0 ctermbg=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#6f6880 guibg=NONE ctermfg=8 ctermbg=NONE gui=NONE cterm=NONE
  hi Whitespace guifg=#2a2438 guibg=NONE ctermfg=0 ctermbg=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#6f6880 guibg=NONE ctermfg=8 ctermbg=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#ff2d95 guibg=#191522 ctermfg=13 ctermbg=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#191522 ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#191522 ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=#191522 ctermfg=NONE ctermbg=0 gui=NONE cterm=NONE
  hi SignColumn guifg=#9c93ab guibg=NONE ctermfg=8 ctermbg=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#6f6880 guibg=NONE ctermfg=8 ctermbg=NONE gui=NONE cterm=NONE
  hi Folded guifg=#9c93ab guibg=#191522 ctermfg=8 ctermbg=NONE gui=italic cterm=italic
  hi WinSeparator guifg=#2a2438 guibg=NONE ctermfg=0 ctermbg=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#2a2438 guibg=NONE ctermfg=0 ctermbg=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#ebe6f0 guibg=#16131d ctermfg=NONE ctermbg=0 gui=NONE cterm=NONE
  hi StatusLineNC guifg=#9c93ab guibg=#0f0d14 ctermfg=8 ctermbg=NONE gui=NONE cterm=NONE
  hi StatusLineTerm guifg=#ebe6f0 guibg=#16131d ctermfg=NONE ctermbg=0 gui=NONE cterm=NONE
  hi StatusLineTermNC guifg=#9c93ab guibg=#0f0d14 ctermfg=8 ctermbg=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#9c93ab guibg=#16131d ctermfg=8 ctermbg=0 gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=#0f0d14 ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#ff2d95 guibg=#0f0d14 ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#ebe6f0 guibg=#16131d ctermfg=NONE ctermbg=0 gui=NONE cterm=NONE
  hi PmenuSel guifg=#ff2d95 guibg=#351229 ctermfg=0 ctermbg=5 gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#16131d ctermfg=NONE ctermbg=0 gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#6f6880 ctermfg=NONE ctermbg=8 gui=NONE cterm=NONE
  hi WildMenu guifg=#ff2d95 guibg=#351229 ctermfg=0 ctermbg=5 gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#57173b ctermfg=NONE ctermbg=0 gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#57173b ctermfg=NONE ctermbg=0 gui=NONE cterm=NONE
  hi Search guifg=#0f0d14 guibg=#b48cff ctermfg=0 ctermbg=5 gui=NONE cterm=NONE
  hi CurSearch guifg=#0f0d14 guibg=#ff2d95 ctermfg=0 ctermbg=13 gui=NONE cterm=NONE
  hi IncSearch guifg=#0f0d14 guibg=#ff2d95 ctermfg=0 ctermbg=13 gui=NONE cterm=NONE
  hi MatchParen guifg=#ff2d95 guibg=#351229 ctermfg=5 ctermbg=NONE gui=underline cterm=underline
  hi QuickFixLine guifg=NONE guibg=#351229 ctermfg=NONE ctermbg=0 gui=NONE cterm=NONE
  hi Title guifg=#b48cff guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi Directory guifg=#b48cff guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi Question guifg=#b48cff guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#b48cff guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#9c93ab guibg=NONE ctermfg=8 ctermbg=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#ff7b72 guibg=NONE ctermfg=1 ctermbg=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#e5c07b guibg=NONE ctermfg=3 ctermbg=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#0f0d14 guibg=#ff2d95 ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi lCursor guifg=#0f0d14 guibg=#ff2d95 ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=NONE guibg=NONE ctermfg=1 ctermbg=NONE gui=undercurl cterm=underline guisp=#ff7b72
  hi SpellCap guifg=NONE guibg=NONE ctermfg=3 ctermbg=NONE gui=undercurl cterm=underline guisp=#e5c07b
  hi SpellRare guifg=NONE guibg=NONE ctermfg=5 ctermbg=NONE gui=undercurl cterm=underline guisp=#b48cff
  hi SpellLocal guifg=NONE guibg=NONE ctermfg=6 ctermbg=NONE gui=undercurl cterm=underline guisp=#9c93ab
  hi DiffAdd guifg=#7ee787 guibg=#141e1a ctermfg=2 ctermbg=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=#ff7b72 guibg=#261419 ctermfg=1 ctermbg=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#241f1e ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi DiffText guifg=#e5c07b guibg=#241f1e ctermfg=3 ctermbg=NONE gui=underline cterm=underline
  hi Comment guifg=#9c93ab guibg=NONE ctermfg=8 ctermbg=NONE gui=italic cterm=italic
  hi Constant guifg=#b48cff guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi String guifg=#e5c07b guibg=NONE ctermfg=3 ctermbg=NONE gui=NONE cterm=NONE
  hi Character guifg=#e5c07b guibg=NONE ctermfg=3 ctermbg=NONE gui=NONE cterm=NONE
  hi Number guifg=#b48cff guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi Boolean guifg=#b48cff guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi Float guifg=#b48cff guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#ebe6f0 guibg=NONE ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi Function guifg=#ebe6f0 guibg=NONE ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#ff2d95 guibg=NONE ctermfg=13 ctermbg=NONE gui=NONE cterm=NONE
  hi Operator guifg=#ebe6f0 guibg=NONE ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#ff2d95 guibg=NONE ctermfg=13 ctermbg=NONE gui=NONE cterm=NONE
  hi Type guifg=#b48cff guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi Special guifg=#b48cff guibg=NONE ctermfg=5 ctermbg=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#ebe6f0 guibg=NONE ctermfg=NONE ctermbg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#b48cff guibg=NONE ctermfg=5 ctermbg=NONE gui=underline cterm=underline
  hi Ignore guifg=#6f6880 guibg=NONE ctermfg=8 ctermbg=NONE gui=NONE cterm=NONE
  hi Error guifg=#ff7b72 guibg=#261419 ctermfg=1 ctermbg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#e5c07b guibg=NONE ctermfg=3 ctermbg=NONE gui=italic cterm=italic
  hi Added guifg=#7ee787 guibg=NONE ctermfg=2 ctermbg=NONE gui=NONE cterm=NONE
  hi Removed guifg=#ff7b72 guibg=NONE ctermfg=1 ctermbg=NONE gui=NONE cterm=NONE
  hi Changed guifg=#e5c07b guibg=NONE ctermfg=3 ctermbg=NONE gui=NONE cterm=NONE
endif

hi! link diffAdded Added
hi! link diffRemoved Removed
hi! link diffChanged Changed
hi! link diffLine Title
hi! link diffFile Comment
hi! link diffIndexLine Comment
hi! link diffSubname Comment
hi! link helpHyperTextJump Underlined
hi! link helpOption Constant
hi! link gitcommitSummary Normal
hi! link Terminal Normal
hi! link ToolbarLine TabLineFill
hi! link ToolbarButton TabLine

" The integrated terminal, :terminal, in the Neon Doll palette.
if &background ==# 'light'
  let g:terminal_ansi_colors = ['#d6cce2', '#c4312a', '#1f7a33', '#8a6100', '#3f5cd0', '#6a3fd0', '#1f6e7a', '#3c3649', '#5f5670', '#802627', '#1d522c', '#5d430e', '#30408a', '#4a2e8a', '#1d4a57', '#1a1522']
else
  let g:terminal_ansi_colors = ['#2a2438', '#ff7b72', '#7ee787', '#e5c07b', '#8ca3ff', '#b48cff', '#7ed9e7', '#c4bcce', '#9c93ab', '#f7a6a4', '#aae7b1', '#e7cfaa', '#b2bef9', '#cab0f9', '#aadeeb', '#ebe6f0']
endif
