#!/usr/bin/env python3
"""Build the KDE Plasma and Qt themes.

    tools/build-kde.py            write kde/
    tools/build-kde.py --check    fail if the output is stale

kde/color-schemes/   Plasma color schemes, NeonDollDark and NeonDollLight: the
                     colors every KDE app and Breeze take.
kde/Kvantum/NeonDoll/
                     a Kvantum theme, NeonDoll (light) with NeonDollDark beside
                     it, as Kvantum pairs them: the shapes. Breeze only takes
                     colors; Kvantum draws every widget from an SVG, so this is
                     where the corners go square, the shadows go, the selected
                     row gets its rail and windows get the graph paper. It
                     works outside Plasma too, in any Qt app.
kde/look-and-feel/   Plasma global themes, Neon Doll Dark and Light, which set
                     the color scheme, Kvantum and the cursor in one go, and
                     let Plasma switch between them with the time of day.
kde/konsole/         Konsole color schemes, the Tilix colors entry for entry,
                     and a profile each that carries the fuchsia cursor.
kde/syntax-highlighting/
                     KSyntaxHighlighting themes, for Kate, KWrite, KDevelop
                     and anything else on KTextEditor: the editor schemes'
                     four syntax colors.
kde/qtct/            a palette each for qt5ct and qt6ct, for Qt apps outside
                     Plasma that don't use Kvantum.

Fuchsia is position and purple is interactive at rest, as everywhere else.
The selection is the editors' select-pink wash with ink on it, not a fill:
text selected in a field and the row selected in a list are the same color,
and the list row adds the fuchsia rail on its left.
"""

import json
import sys
from pathlib import Path

import tokens

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "kde"
VARIANTS = tokens.VARIANTS
NAME = {"dark": "Neon Doll Dark", "light": "Neon Doll Light"}
SCHEME = {"dark": "NeonDollDark", "light": "NeonDollLight"}
# Kvantum's pairing: a theme and its dark variant, named THEME and THEMEDark,
# in THEME's folder. The style key "kvantum-dark" picks the dark one of
# whatever theme is set, which is how the dark global theme gets it.
KVANTUM = {"dark": "NeonDollDark", "light": "NeonDoll"}
AUTHOR = "Misha Nasledov"
WEBSITE = "https://github.com/mishan/neon-doll"
LICENSE = "GPL-3.0-or-later"


def colors(variant):
    """The palette, with every tint both flattened (for formats that take
    only solid colors) and as (color, alpha) (for the SVG, which blends)."""
    p = tokens.flat(variant)
    a = {name: tokens.tint(variant, name) for name in tokens.tints(variant)}
    return p, a


def rgb(h):
    return ",".join(map(str, tokens.rgb(h)))


def generated():
    return "Generated by tools/build-kde.py; edit that, not this."


# --- Plasma color schemes ----------------------------------------------------

def disabled_fade(p):
    """Plasma dims disabled text by fading it toward its background. The fade
    that takes ink closest to dimmest, which is what disabled text is on
    every other part of the theme."""
    ink, bg, want = (tokens.rgb(p[k]) for k in ("ink", "bg", "dimmest"))
    num = sum((b - i) * (w - i) for i, b, w in zip(ink, bg, want))
    den = sum((b - i) ** 2 for i, b in zip(ink, bg))
    return round(num / den, 2)


def color_scheme(variant):
    p, _ = colors(variant)
    fg = {
        "DecorationFocus": p["pink"],
        "DecorationHover": p["pink"],
        "ForegroundActive": p["pink"],
        "ForegroundInactive": p["muted"],
        "ForegroundLink": p["purple"],
        "ForegroundNegative": p["del"],
        "ForegroundNeutral": p["string"],
        "ForegroundNormal": p["ink"],
        "ForegroundPositive": p["add"],
        "ForegroundVisited": p["purple"],
    }
    # Each set: its background, and the alternate one.
    sets = {
        "Button": (p["wash"], p["wash-pink"]),
        "Complementary": (p["panel"], p["bg"]),
        "Header": (p["panel"], p["bg"]),
        "Header][Inactive": (p["bg"], p["panel"]),
        "Selection": (p["select"], p["wash-pink"]),
        "Tooltip": (p["panel"], p["bg"]),
        "View": (p["bg"], p["wash"]),
        "Window": (p["bg"], p["panel"]),
    }
    out = [
        f"# {NAME[variant]}, a Plasma color scheme. {generated()}",
        "#",
        "# The window and the views are the page; the header, tooltips and",
        "# alternate rows are the panel. Fuchsia is focus and hover, purple is",
        "# links, and the selection is a fuchsia wash with ink on it.",
        "",
        "[ColorEffects:Disabled]",
        f"Color={rgb(p['bg'])}",
        "ColorAmount=0",
        "ColorEffect=0",
        f"ContrastAmount={disabled_fade(p)}",
        "ContrastEffect=1",
        "IntensityAmount=0",
        "IntensityEffect=0",
        "",
        "[ColorEffects:Inactive]",
        "ChangeSelectionColor=false",
        f"Color={rgb(p['bg'])}",
        "ColorAmount=0",
        "ColorEffect=0",
        "ContrastAmount=0",
        "ContrastEffect=0",
        "Enable=false",
        "IntensityAmount=0",
        "IntensityEffect=0",
        "",
    ]
    for name, (bg, alt) in sets.items():
        keys = {"BackgroundAlternate": alt, "BackgroundNormal": bg, **fg}
        if name == "Selection":
            keys["ForegroundActive"] = p["ink"]
        out.append(f"[Colors:{name}]")
        out += [f"{k}={rgb(v)}" for k, v in sorted(keys.items())]
        out.append("")
    out += [
        "[General]",
        f"ColorScheme={SCHEME[variant]}",
        f"Name={NAME[variant]}",
        "shadeSortColumn=false",
        "",
        "[KDE]",
        "contrast=4",
        "",
        "[WM]",
        f"activeBackground={rgb(p['panel'])}",
        f"activeBlend={rgb(p['pink'])}",
        f"activeForeground={rgb(p['ink'])}",
        f"inactiveBackground={rgb(p['bg'])}",
        f"inactiveBlend={rgb(p['muted'])}",
        f"inactiveForeground={rgb(p['muted'])}",
        "",
    ]
    return "\n".join(out)


# --- Kvantum -----------------------------------------------------------------
#
# A Kvantum theme is a config and an SVG. Each widget section names SVG
# elements; a boxed element is nine pieces, the interior "NAME-STATE" and the
# frame "NAME-STATE-top", "-topleft" and so on, which Kvantum stretches to the
# frame widths the section gives. So the frame widths here and the pieces in
# the SVG come from the same table, and a 1px line in the SVG is 1px on screen.
# States are normal, focused (hover), pressed, toggled and disabled; a missing
# state falls back to normal, and a missing normal to Kvantum's default theme,
# which has gradients, so every element named here has a normal.

class Svg:
    """Elements packed onto a sheet, left to right, in rows."""

    def __init__(self):
        self.body, self.x, self.y, self.row = [], 0, 0, 0

    def place(self, w, h):
        gap = 4
        if self.x + w > 1000:
            self.x, self.y, self.row = 0, self.y + self.row + gap, 0
        at = (self.x, self.y)
        self.x += w + gap
        self.row = max(self.row, h)
        return at

    def group(self, id, x, y, w, h, shapes):
        """One element: an invisible rect that fixes its bounds, then its
        shapes, which are in the element's own coordinates."""
        out = [f'<g id="{id}">', f'<rect x="{x}" y="{y}" width="{w}" height="{h}" fill="#000" fill-opacity="0"/>']
        for s in shapes:
            out.append(s(x, y))
        out.append("</g>")
        self.body.append("".join(out))

    def element(self, id, w, h, shapes):
        x, y = self.place(w, h)
        self.group(id, x, y, w, h, shapes)

    def svg(self, comment):
        height = self.y + self.row
        return (
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            f"<!-- {comment} -->\n"
            f'<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="{height}" '
            f'viewBox="0 0 1000 {height}">\n' + "\n".join(self.body) + "\n</svg>\n"
        )


def paint(c):
    """(color, alpha) or a plain color, as SVG fill attributes."""
    color, alpha = c if isinstance(c, tuple) else (c, 1)
    return f'fill="{color}"' + (f' fill-opacity="{alpha:g}"' if alpha < 1 else "")


def rect(x, y, w, h, c):
    return lambda ox, oy: f'<rect x="{ox + x:g}" y="{oy + y:g}" width="{w:g}" height="{h:g}" {paint(c)}/>'


def circle(cx, cy, r, c):
    return lambda ox, oy: f'<circle cx="{ox + cx:g}" cy="{oy + cy:g}" r="{r:g}" {paint(c)}/>'


def ring(cx, cy, r, width, c):
    color, alpha = c if isinstance(c, tuple) else (c, 1)
    op = f' stroke-opacity="{alpha:g}"' if alpha < 1 else ""
    return lambda ox, oy: (f'<circle cx="{ox + cx:g}" cy="{oy + cy:g}" r="{r - width / 2:g}" fill="none" '
                           f'stroke="{color}" stroke-width="{width:g}"{op}/>')


def line(points, c, width=2):
    """A stroked polyline, square-ended and mitered: no round corners here
    either."""
    def f(ox, oy):
        d = "M" + " L".join(f"{ox + x:g},{oy + y:g}" for x, y in points)
        return (f'<path d="{d}" fill="none" stroke="{c}" stroke-width="{width:g}" '
                'stroke-linecap="square" stroke-linejoin="miter"/>')
    return f


def box(svg, name, state, frame, fill=None, edges=None, inset=(0, 0, 0, 0), core=8):
    """A nine-piece element. frame is (top, bottom, left, right), as in the
    config; fill covers the box, frame included unless inset keeps it off,
    so padding in the frame reads as interior; edges maps a side to (width,
    color), drawn over the fill at the outside of that side. A state of None
    is for the stateless elements, like the focus frame."""
    t, b, l, r = frame
    w, h = l + core + r, t + core + b
    edges = edges or {}
    it, ib, il, ir = inset
    layers = [(il, it, w - il - ir, h - it - ib, fill)] if fill else []
    et = edges.get("top", (0, None))[0]
    eb = edges.get("bottom", (0, None))[0]
    for side, (ew, c) in edges.items():
        if not ew:
            continue
        layers.append({
            "top": (0, 0, w, ew, c),
            "bottom": (0, h - ew, w, ew, c),
            "left": (0, et, ew, h - et - eb, c),
            "right": (w - ew, et, ew, h - et - eb, c),
        }[side])
    pieces = {
        "topleft": (0, 0, l, t), "top": (l, 0, core, t), "topright": (l + core, 0, r, t),
        "left": (0, t, l, core), "": (l, t, core, core), "right": (l + core, t, r, core),
        "bottomleft": (0, t + core, l, b), "bottom": (l, t + core, core, b),
        "bottomright": (l + core, t + core, r, b),
    }
    ox, oy = svg.place(w, h)
    for pos, (px, py, pw, ph) in pieces.items():
        if pw <= 0 or ph <= 0:
            continue
        shapes = []
        for lx, ly, lw, lh, c in layers:
            x0, y0 = max(px, lx), max(py, ly)
            x1, y1 = min(px + pw, lx + lw), min(py + ph, ly + lh)
            if x1 > x0 and y1 > y0:
                shapes.append(rect(x0 - px, y0 - py, x1 - x0, y1 - y0, c))
        id = (name if state is None else f"{name}-{state}") + (f"-{pos}" if pos else "")
        svg.group(id, ox + px, oy + py, pw, ph, shapes)


def outline(width, c, sides=("top", "bottom", "left", "right")):
    return {s: (width, c) for s in sides}


# Frame widths, (top, bottom, left, right), shared by the config and the SVG.
FRAMES = {
    "button": (1, 1, 1, 1),
    "combo": (1, 1, 1, 1),
    "toolbutton": (1, 1, 1, 1),
    "lineedit": (2, 2, 2, 2),
    "common": (1, 1, 1, 1),
    "group": (1, 1, 1, 1),
    "focus": (1, 1, 1, 1),
    "tab": (2, 1, 1, 1),
    "tabframe": (1, 1, 1, 1),
    "header": (0, 1, 0, 1),
    "toolbar": (1, 1, 1, 1),
    "itemview": (0, 0, 2, 0),
    "scrollslider": (0, 0, 2, 2),
    "menu": (1, 1, 1, 1),
    "tooltip": (1, 1, 1, 1),
}


def kvantum_svg(variant):
    p, a = colors(variant)
    pink, ink, muted, dimmest, line_ = (p[k] for k in ("pink", "ink", "muted", "dimmest", "line"))
    bg, panel = p["bg"], p["panel"]
    wash, press, wash_pink = a["wash"], a["press"], a["wash-pink"]
    clear = (bg, 0)
    s = Svg()
    F = FRAMES

    # Push buttons: a purple wash with a hairline edge; hover and focus turn
    # the edge fuchsia, checked is a fuchsia wash. The default button is the
    # suggested action: its edge is purple.
    box(s, "button", "normal", F["button"], wash, outline(1, line_))
    box(s, "button", "focused", F["button"], wash, outline(1, pink))
    box(s, "button", "pressed", F["button"], press, outline(1, pink))
    box(s, "button", "toggled", F["button"], wash_pink, outline(1, line_))
    box(s, "button-default", None, F["button"], wash, outline(1, a["tint-purple"]))
    box(s, "button-focus", None, F["button"], None, outline(1, pink))
    s.element("button-default-indicator", 8, 8, [])

    # Drop-downs are fields you choose from: a panel, like a text field.
    box(s, "combo", "normal", F["combo"], panel, outline(1, line_))
    box(s, "combo", "focused", F["combo"], panel, outline(1, pink))
    box(s, "combo", "pressed", F["combo"], panel, outline(1, pink))
    box(s, "combo", "toggled", F["combo"], panel, outline(1, pink))

    # Buttons on a toolbar are flat until you point at them.
    box(s, "toolbutton", "normal", F["toolbutton"], clear)
    box(s, "toolbutton", "focused", F["toolbutton"], wash)
    box(s, "toolbutton", "pressed", F["toolbutton"], press)
    box(s, "toolbutton", "toggled", F["toolbutton"], wash_pink)

    # Fields: a panel with a hairline; focus is a 2px fuchsia ring, and the
    # ring is the whole state.
    box(s, "lineedit", "normal", F["lineedit"], panel, outline(1, line_))
    box(s, "lineedit", "focused", F["lineedit"], panel, outline(2, pink))

    # Frames and cards.
    box(s, "common", "normal", F["common"], None, outline(1, line_))
    box(s, "group", "normal", F["group"], panel, outline(1, line_))
    box(s, "focus", None, F["focus"], None, outline(1, pink))

    # Tabs: muted labels on a hairline; the current tab is the page, open to
    # its contents, with a 2px fuchsia rail across its top.
    box(s, "tab", "normal", F["tab"], clear, {"bottom": (1, line_)})
    box(s, "tab", "focused", F["tab"], wash, {"bottom": (1, line_)})
    box(s, "tab", "pressed", F["tab"], press, {"bottom": (1, line_)})
    box(s, "tab", "toggled", F["tab"], bg, {"top": (2, pink), "left": (1, line_), "right": (1, line_)})
    # Keyboard focus on a tab outlines it in fuchsia, open at the bottom.
    box(s, "tab-focus", None, F["tab"], None, outline(1, pink, ("top", "left", "right")))
    box(s, "tabframe", "normal", F["tabframe"], None, outline(1, line_))
    s.element("tab-tear", 2, 16, [rect(0, 0, 2, 16, line_)])

    # Column headers: the page, with a hairline under them and between them.
    box(s, "header", "normal", F["header"], bg, {"bottom": (1, line_)})
    box(s, "header", "focused", F["header"], wash, {"bottom": (1, line_)})
    box(s, "header", "pressed", F["header"], press, {"bottom": (1, line_)})
    s.element("header-separator", 1, 16, [rect(0, 0, 1, 16, line_)])

    # Toolbars (and the menu bar, merged with them) are the panel, with a
    # hairline under them.
    box(s, "toolbar", "normal", F["toolbar"], panel, {"bottom": (1, line_)})
    s.element("toolbar-handle", 8, 16, [rect(3, y, 2, 2, dimmest) for y in (3, 7, 11)])
    s.element("toolbar-separator", 9, 16, [rect(4, 0, 1, 16, line_)])

    # The selected row: a fuchsia wash with a 2px fuchsia rail on its left.
    # Hover is the purple wash.
    box(s, "itemview", "focused", F["itemview"], wash)
    box(s, "itemview", "pressed", F["itemview"], press)
    box(s, "itemview", "toggled", F["itemview"], wash_pink, {"left": (2, pink)})

    # Scrollbars: a bare slider in the dimmest grey, fuchsia while dragged;
    # no trough, no arrows.
    for state, c in (("normal", dimmest), ("focused", muted), ("pressed", pink)):
        box(s, "scrollslider", state, F["scrollslider"], c, inset=F["scrollslider"])
    s.element("scrollgroove-normal", 8, 8, [])
    for state in ("normal", "focused", "pressed"):
        s.element(f"grip-{state}", 8, 8, [])

    # Menus and tooltips: the panel with a hairline, no shadow.
    box(s, "menu", "normal", F["menu"], panel, outline(1, line_))
    box(s, "tooltip", "normal", F["tooltip"], panel, outline(1, line_))
    for state in ("focused", "pressed", "toggled"):
        s.element(f"menuitem-{state}", 8, 8, [rect(0, 0, 8, 8, wash)])
    s.element("menuitem-separator", 16, 9, [rect(0, 4, 16, 1, line_)])
    for state in ("normal", "focused"):
        s.element(f"menuitem-tearoff-{state}", 20, 8, [rect(x, 3, 3, 1, dimmest) for x in (0, 5, 10, 15)])
    s.element("menubar-normal", 8, 8, [rect(0, 0, 8, 8, panel)])
    s.element("menubaritem-focused", 8, 8, [rect(0, 0, 8, 8, wash)])
    for state in ("pressed", "toggled"):
        s.element(f"menubaritem-{state}", 8, 8, [rect(0, 0, 8, 8, wash_pink)])

    # Sliders: the groove a hairline-thin line, filled fuchsia up to the
    # handle; the handle an upright ink bar, fuchsia while held.
    s.element("slider-normal", 8, 8, [rect(0, 0, 8, 8, line_)])
    s.element("slider-toggled", 8, 8, [rect(0, 0, 8, 8, pink)])
    s.element("slider-tick-normal", 5, 1, [rect(0, 0, 5, 1, dimmest)])
    for state, c in (("normal", ink), ("focused", ink), ("pressed", pink), ("disabled", line_)):
        s.element(f"slidercursor-{state}", 18, 10, [rect(0, 0, 18, 10, c)])

    # Progress: a line-colored groove, the bar fuchsia.
    s.element("progress-normal", 8, 8, [rect(0, 0, 8, 8, line_)])
    s.element("progress-pattern-normal", 8, 8, [rect(0, 0, 8, 8, pink)])
    s.element("progress-pattern-disabled", 8, 8, [rect(0, 0, 8, 8, dimmest)])

    # Splitters: a hairline, fuchsia while dragged. (Dolphin sizes its
    # status bar from the splitter width, and a wider one crops its text.)
    for state, c in (("normal", line_), ("focused", pink), ("pressed", pink)):
        s.element(f"splitter-{state}", 1, 16, [rect(0, 0, 1, 16, c)])
    for state in ("normal", "focused", "pressed"):
        s.element(f"splitter-grip-{state}", 8, 8, [])

    # Title bars of dock widgets and MDI windows: the panel.
    for state in ("normal", "focused"):
        s.element(f"titlebar-{state}", 8, 8, [rect(0, 0, 8, 8, panel)])
    s.element("docktitle-normal", 8, 8, [rect(0, 0, 8, 8, panel)])

    # Windows and dialogs: the page, with the graph paper over it.
    s.element("window-normal", 24, 24, [rect(0, 0, 24, 24, bg)])
    s.element("window-normal-pattern", 24, 24, [rect(0, 0, 24, 1, a["grid"]), rect(0, 1, 1, 23, a["grid"])])

    s.element("sizegrip-normal", 13, 13, [rect(x, y, 2, 2, dimmest) for x, y in
                                          ((10, 2), (6, 6), (10, 6), (2, 10), (6, 10), (10, 10))])

    # Check boxes and radios: a muted outline, fuchsia under the pointer;
    # checked, a fuchsia fill with the mark cut out of it in the page color.
    # Radios keep their circle: round against square is how you tell them
    # apart.
    def check(state, outline_c, fill=None, mark=None):
        shapes = [rect(0, 0, 16, 16, fill)] if fill else [
            rect(0, 0, 16, 1, outline_c), rect(0, 15, 16, 1, outline_c),
            rect(0, 1, 1, 14, outline_c), rect(15, 1, 1, 14, outline_c)]
        if mark == "check":
            shapes.append(line([(4, 8), (7, 11), (12, 5)], bg, 2))
        elif mark == "tristate":
            shapes.append(rect(4, 7, 8, 2, bg))
        s.element(f"checkbox-{state}", 16, 16, shapes)

    def radio(state, outline_c, fill=None, dot=False):
        shapes = [circle(8, 8, 8, fill)] if fill else [ring(8, 8, 8, 1, outline_c)]
        if dot:
            shapes.append(circle(8, 8, 3, bg))
        s.element(f"radio-{state}", 16, 16, shapes)

    for state, c in (("normal", muted), ("focused", pink), ("pressed", pink), ("disabled", line_)):
        check(state, c)
        radio(state, c)
    for state, c in (("normal", pink), ("focused", pink), ("pressed", pink), ("disabled", line_)):
        check(f"checked-{state}", c, c, "check")
        check(f"tristate-{state}", c, c, "tristate")
        radio(f"checked-{state}", c, c, True)

    # Indicators, drawn on a 16px square: ink at rest, fuchsia under the
    # pointer or held, the dimmest grey when disabled.
    states = (("normal", ink), ("focused", pink), ("pressed", pink), ("toggled", pink), ("disabled", dimmest))

    def glyph(id, kind, c):
        shapes = {
            "up": [line([(4, 10), (8, 6), (12, 10)], c)],
            "down": [line([(4, 6), (8, 10), (12, 6)], c)],
            "left": [line([(10, 4), (6, 8), (10, 12)], c)],
            "right": [line([(6, 4), (10, 8), (6, 12)], c)],
            "plus": [rect(3, 7, 10, 2, c), rect(7, 3, 2, 10, c)],
            "minus": [rect(3, 7, 10, 2, c)],
            "close": [line([(4, 4), (12, 12)], c, 1.5), line([(12, 4), (4, 12)], c, 1.5)],
            "maximize": [rect(3, 3, 10, 1.5, c), rect(3, 11.5, 10, 1.5, c),
                         rect(3, 3, 1.5, 10, c), rect(11.5, 3, 1.5, 10, c)],
            "restore": [rect(5, 2, 9, 1.5, c), rect(12.5, 2, 1.5, 9, c),
                        rect(2, 5, 9, 1.5, c), rect(2, 12.5, 9, 1.5, c),
                        rect(2, 5, 1.5, 9, c), rect(9.5, 5, 1.5, 9, c)],
            "minimize": [rect(3, 11, 10, 2, c)],
            "shade": [line([(4, 10), (8, 6), (12, 10)], c)],
            "menu": [rect(3, y, 10, 1.5, c) for y in (4, 7.25, 10.5)],
        }[kind]
        s.element(id, 16, 16, shapes)

    for d in ("up", "down", "left", "right", "plus", "minus"):
        for state, c in states:
            glyph(f"arrow-{d}-{state}", d, c)
    # Tree branches: a chevron, muted, pointing where the branch goes.
    for d, kind in (("plus", "right"), ("minus", "down")):
        for state, c in (("normal", muted), ("focused", pink), ("pressed", pink), ("disabled", dimmest)):
            glyph(f"tree-{d}-{state}", kind, c)
    for state, c in (("normal", muted), ("focused", pink), ("pressed", pink), ("disabled", dimmest), ("toggled", ink)):
        glyph(f"tab-close-{state}", "close", c)
    for kind in ("close", "maximize", "restore", "minimize", "shade"):
        for state, c in (("normal", muted), ("focused", pink), ("pressed", pink), ("disabled", dimmest)):
            glyph(f"mdi-{kind}-{state}", kind, c)
    glyph("mdi-menu-normal", "menu", muted)

    # Dials, which almost nothing uses: a ring, and a fuchsia handle.
    s.element("dial", 32, 32, [circle(16, 16, 16, panel), ring(16, 16, 16, 1, line_)])
    s.element("dial-notches", 32, 32, [])
    s.element("dial-handle", 8, 8, [circle(4, 4, 4, pink)])

    return s.svg(f"{NAME[variant]}, for Kvantum. {generated()}")


def kvantum_config(variant):
    p, _ = colors(variant)
    F = FRAMES
    ink, pink, muted = p["ink"], p["pink"], p["muted"]

    def frame(name):
        t, b, l, r = F[name]
        return {"frame.top": t, "frame.bottom": b, "frame.left": l, "frame.right": r}

    def texts(normal=ink, focus=pink, press=pink, toggle=pink):
        return {"text.normal.color": normal, "text.focus.color": focus,
                "text.press.color": press, "text.toggle.color": toggle}

    sections = {
        "%General": {
            "author": AUTHOR,
            "comment": f"{NAME[variant]}: hot pink neon on midnight plum",
            "respect_DE": "true",
            "x11drag": "menubar_and_primary_toolbar",
            "alt_mnemonic": "true",
            "composite": "false",
            "animate_states": "false",
            "no_inactiveness": "true",
            "left_tabs": "true",
            "attach_active_tab": "true",
            "joined_inactive_tabs": "true",
            "group_toolbar_buttons": "false",
            "merge_menubar_with_toolbar": "true",
            "center_toolbar_handle": "true",
            "toolbar_separator_thickness": 9,
            "spread_progressbar": "true",
            "progressbar_thickness": 6,
            "spread_menuitems": "true",
            "menu_separator_height": 9,
            "menu_shadow_depth": 0,
            "tooltip_shadow_depth": 0,
            "splitter_width": 1,
            "scroll_width": 10,
            "scroll_min_extent": 36,
            "scroll_arrows": "false",
            "scrollbar_in_view": "true",
            "transient_scrollbar": "false",
            "combo_as_lineedit": "true",
            "inline_spin_indicators": "true",
            "slider_width": 4,
            "slider_handle_width": 18,
            "slider_handle_length": 10,
            "check_size": 16,
            "groupbox_top_label": "true",
            "tree_branch_line": "false",
            "layout_spacing": 6,
            "layout_margin": 6,
            "dark_titlebar": "true" if variant == "dark" else "false",
        },
        "GeneralColors": {
            "window.color": p["bg"],
            "base.color": p["bg"],
            "alt.base.color": p["wash"],
            "button.color": p["wash"],
            "light.color": p["line"],
            "mid.light.color": p["line"],
            "dark.color": p["bg"],
            "mid.color": p["line"],
            "shadow.color": p["bg"],
            "highlight.color": p["select"],
            "inactive.highlight.color": p["press"],
            "tooltip.base.color": p["panel"],
            "text.color": ink,
            "window.text.color": ink,
            "button.text.color": ink,
            "disabled.text.color": p["dimmest"],
            "tooltip.text.color": ink,
            "highlight.text.color": ink,
            "link.color": p["purple"],
            "link.visited.color": p["purple"],
            "progress.indicator.text.color": ink,
        },
        "Hacks": {
            "respect_darkness": "true",
            "transparent_ktitle_label": "true",
            "transparent_menutitle": "true",
            "normal_default_pushbutton": "true",
            "no_selection_tint": "true",
        },
        "PanelButtonCommand": {
            "frame": "true", "frame.element": "button", **frame("button"),
            "interior": "true", "interior.element": "button",
            "focusFrame": "true",
            "indicator.element": "arrow", "indicator.size": 10,
            "text.margin.top": 3, "text.margin.bottom": 3,
            "text.margin.left": 8, "text.margin.right": 8,
            "text.iconspacing": 6,
            **texts(),
        },
        "PanelButtonTool": {"inherits": "PanelButtonCommand"},
        "ToolbarButton": {
            "frame.element": "toolbutton", "interior.element": "toolbutton",
            "indicator.element": "arrow", **texts(),
        },
        "ComboBox": {
            "inherits": "PanelButtonCommand",
            "frame.element": "combo", "interior.element": "combo",
            "text.margin.left": 6, "text.margin.right": 6,
            **texts(focus=pink, press=ink, toggle=ink),
        },
        "ToolbarComboBox": {"frame.element": "combo", "interior.element": "combo", **texts(press=ink, toggle=ink)},
        "LineEdit": {
            "inherits": "PanelButtonCommand",
            "frame.element": "lineedit", "interior.element": "lineedit", **frame("lineedit"),
            "focusFrame": "false",
            "text.margin.top": 2, "text.margin.bottom": 2,
            "text.margin.left": 4, "text.margin.right": 4,
        },
        "ToolbarLineEdit": {"frame.element": "lineedit", "interior.element": "lineedit"},
        "IndicatorSpinBox": {
            "inherits": "PanelButtonCommand",
            "frame.element": "button", "interior.element": "button",
            "indicator.element": "arrow", "indicator.size": 10,
        },
        "DropDownButton": {"inherits": "PanelButtonCommand", "indicator.element": "arrow-down"},
        "IndicatorArrow": {"indicator.element": "arrow", "indicator.size": 10},
        "RadioButton": {
            "inherits": "PanelButtonCommand", "frame": "false", "focusFrame": "false",
            "interior.element": "radio", "text.margin.left": 4, "text.margin.right": 4,
            **texts(focus=ink, press=ink, toggle=ink),
        },
        "CheckBox": {
            "inherits": "PanelButtonCommand", "frame": "false", "focusFrame": "false",
            "interior.element": "checkbox", "text.margin.left": 4, "text.margin.right": 4,
            **texts(focus=ink, press=ink, toggle=ink),
        },
        "Focus": {
            "frame": "true", "frame.element": "focus", **frame("focus"),
            "interior": "false", "frame.patternsize": 0,
        },
        "GenericFrame": {
            "frame": "true", "frame.element": "common", **frame("common"),
            "interior": "false",
        },
        "GroupBox": {
            "inherits": "GenericFrame",
            "frame.element": "group", "interior": "true", "interior.element": "group", **frame("group"),
            "text.margin": 0,
            **texts(normal=muted, focus=muted, press=muted, toggle=muted),
        },
        "TabFrame": {
            "frame": "true", "frame.element": "tabframe", **frame("tabframe"),
            "interior": "false",
        },
        "TabBarFrame": {"frame": "false", "interior": "false"},
        "Tab": {
            "frame": "true", "frame.element": "tab", **frame("tab"),
            "interior": "true", "interior.element": "tab",
            "indicator.element": "tab", "indicator.size": 14,
            "text.margin.top": 4, "text.margin.bottom": 4,
            "text.margin.left": 10, "text.margin.right": 10,
            "focusFrame": "true",
            **texts(normal=muted, focus=pink, press=pink, toggle=ink),
        },
        "ToolboxTab": {"inherits": "PanelButtonCommand"},
        "TreeExpander": {
            "frame": "false", "interior": "false",
            "indicator.element": "tree", "indicator.size": 12,
        },
        "HeaderSection": {
            "inherits": "PanelButtonCommand",
            "frame.element": "header", "interior.element": "header", **frame("header"),
            "focusFrame": "false",
            "indicator.element": "arrow", "indicator.size": 10,
            "text.margin.top": 3, "text.margin.bottom": 3,
            "text.margin.left": 6, "text.margin.right": 6,
            **texts(normal=muted, focus=pink, press=pink, toggle=muted),
        },
        "SizeGrip": {"indicator.element": "sizegrip", "indicator.size": 13},
        "Toolbar": {
            "frame": "true", "frame.element": "toolbar", **frame("toolbar"),
            "interior": "true", "interior.element": "toolbar",
            "indicator.element": "toolbar", "indicator.size": 8,
            "text.margin": 0,
            **texts(),
        },
        "MenuBar": {
            "frame": "false", "interior": "true", "interior.element": "menubar",
            **texts(),
        },
        "MenuBarItem": {
            "frame": "false", "interior": "true", "interior.element": "menubaritem",
            "text.margin.top": 3, "text.margin.bottom": 3,
            "text.margin.left": 8, "text.margin.right": 8,
            **texts(),
        },
        "Menu": {
            "frame": "true", "frame.element": "menu", **frame("menu"),
            "interior": "true", "interior.element": "menu",
            **texts(),
        },
        "MenuItem": {
            "frame": "false", "interior": "true", "interior.element": "menuitem",
            "indicator.element": "menuitem", "indicator.size": 10,
            "text.margin.top": 3, "text.margin.bottom": 3,
            "text.margin.left": 6, "text.margin.right": 6,
            "min_height": 24,
            **texts(),
        },
        "ToolTip": {
            "frame": "true", "frame.element": "tooltip", **frame("tooltip"),
            "interior": "true", "interior.element": "tooltip",
            "text.margin.top": 3, "text.margin.bottom": 3,
            "text.margin.left": 6, "text.margin.right": 6,
            **texts(focus=ink, press=ink, toggle=ink),
        },
        "ItemView": {
            "frame": "true", "frame.element": "itemview", **frame("itemview"),
            "interior": "true", "interior.element": "itemview",
            "text.margin.top": 2, "text.margin.bottom": 2,
            "text.margin.left": 4, "text.margin.right": 4,
            **texts(focus=pink, press=ink, toggle=ink),
        },
        "Splitter": {
            "frame": "false", "interior": "true", "interior.element": "splitter",
            "indicator.element": "splitter-grip", "indicator.size": 16,
        },
        "Scrollbar": {"indicator.element": "arrow", "indicator.size": 8},
        "ScrollbarGroove": {"frame": "false", "interior": "true", "interior.element": "scrollgroove"},
        "ScrollbarSlider": {
            "frame": "true", "frame.element": "scrollslider", **frame("scrollslider"),
            "interior": "true", "interior.element": "scrollslider",
            "indicator.element": "grip", "indicator.size": 8,
        },
        "Slider": {
            "frame": "false", "interior": "true", "interior.element": "slider",
        },
        "SliderCursor": {"frame": "false", "interior": "true", "interior.element": "slidercursor"},
        "Progressbar": {
            "frame": "false", "interior": "true", "interior.element": "progress",
            "text.margin": 0, **texts(focus=ink, press=ink, toggle=ink),
        },
        "ProgressbarContents": {
            "frame": "false", "interior": "true", "interior.element": "progress-pattern",
        },
        "TitleBar": {
            "frame": "false", "interior": "true", "interior.element": "titlebar",
            "indicator.element": "mdi", "indicator.size": 14,
            **texts(normal=ink, focus=ink, press=ink, toggle=ink),
        },
        "Dock": {"frame": "false", "interior": "false"},
        "DockTitle": {
            "frame": "false", "interior": "true", "interior.element": "docktitle",
            "text.margin.top": 3, "text.margin.bottom": 3,
            "text.margin.left": 6, "text.margin.right": 6,
            **texts(normal=muted, focus=muted, press=muted, toggle=muted),
        },
        "StatusBar": {"frame": "false", "interior": "false"},
        "Window": {
            "interior": "true", "interior.element": "window",
            "interior.x.patternsize": 24, "interior.y.patternsize": 24,
        },
    }
    out = [f"# {NAME[variant]}, for Kvantum. {generated()}", ""]
    for name, keys in sections.items():
        out.append(f"[{name}]")
        out += [f"{k}={v}" for k, v in keys.items()]
        out.append("")
    return "\n".join(out)


# --- Plasma global themes ------------------------------------------------------

# A QFont, as kdeglobals stores one: the fontconfig alias, at 9pt, weight 400.
MONO = "monospace,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"

def look_and_feel(variant):
    lf_id = f"io.github.mishan.neon-doll-{variant}"
    meta = {
        "KPackageStructure": "Plasma/LookAndFeel",
        "KPlugin": {
            "Authors": [{"Name": AUTHOR}],
            "Category": "",
            "Description": f"Hot pink neon on midnight plum, {variant}",
            "Id": lf_id,
            "License": LICENSE,
            "Name": NAME[variant],
            "Website": WEBSITE,
        },
        "X-Plasma-APIVersion": "2",
    }
    defaults = "\n".join([
        f"# {NAME[variant]}, a Plasma global theme. {generated()}",
        "#",
        "# The color scheme, Kvantum (whose dark style key picks NeonDollDark",
        "# from the NeonDoll theme), the chrome fonts and the cursor. Window",
        "# decorations and the Plasma style stay Breeze's, which take the color",
        "# scheme's colors.",
        "",
        "[kdeglobals][KDE]",
        f"widgetStyle={'kvantum-dark' if variant == 'dark' else 'kvantum'}",
        "",
        "[kdeglobals][General]",
        f"ColorScheme={SCHEME[variant]}",
        "# Mono is the chrome: toolbars, menus and window titles, in whatever",
        "# monospace font the system has, a point under the sans. Sans is left",
        "# on what you read.",
        f"menuFont={MONO}",
        f"toolBarFont={MONO}",
        "# Not read from here: Plasma 6 looks for activeFont under General (and",
        "# the other fonts under WM) to decide whether a global theme has fonts",
        "# at all, then reads them from where they belong.",
        f"activeFont={MONO}",
        "",
        "[kdeglobals][WM]",
        f"activeFont={MONO}",
        "",
        "[kdeglobals][Icons]",
        f"Theme={'breeze-dark' if variant == 'dark' else 'breeze'}",
        "",
        "[plasmarc][Theme]",
        "name=default",
        "",
        "[kcminputrc][Mouse]",
        "cursorTheme=Neon-Doll-Cursors",
        "",
        "[kwinrc][org.kde.kdecoration2]",
        "library=org.kde.breeze",
        "theme=Breeze",
        "",
        "# This package has no splash screen of its own; without this, Plasma",
        "# would look for one in it.",
        "[ksplashrc][KSplash]",
        "Theme=org.kde.breeze.desktop",
        "",
    ])
    base = OUT / "look-and-feel" / lf_id
    yield base / "metadata.json", json.dumps(meta, indent=4) + "\n"
    yield base / "contents" / "defaults", defaults


# --- Konsole -------------------------------------------------------------------

def tilix(variant):
    return json.loads((ROOT / "tilix" / f"neon-doll-{variant}.json").read_text())


def konsole_scheme(variant):
    t, p = tilix(variant), tokens.palette(variant)
    ansi, bg = t["palette"], t["background-color"]
    out = [f"# {NAME[variant]}, a Konsole color scheme: the Tilix colors. {generated()}", ""]

    def entry(name, color):
        out.extend([f"[{name}]", f"Color={rgb(color)}", ""])

    entry("Background", bg)
    entry("BackgroundFaint", bg)
    entry("BackgroundIntense", bg)
    for i in range(8):
        entry(f"Color{i}", ansi[i])
        entry(f"Color{i}Faint", tokens.over(bg, ansi[i], 0.7))
        entry(f"Color{i}Intense", ansi[i + 8])
    entry("Foreground", t["foreground-color"])
    entry("ForegroundFaint", p["muted"])
    entry("ForegroundIntense", p["ink"])
    out += [
        "[General]",
        "Anchor=0.5,0.5",
        "Blur=false",
        "ColorRandomization=false",
        f"Description={NAME[variant]}",
        "FillStyle=Tile",
        "Opacity=1",
        "Wallpaper=",
        "WallpaperFlipType=NoFlip",
        "WallpaperOpacity=1",
        "",
    ]
    return "\n".join(out)


def konsole_profile(variant):
    t = tilix(variant)
    return "\n".join([
        f"# {NAME[variant]}, a Konsole profile. {generated()}",
        "# A color scheme can't set the cursor color; a profile can.",
        "",
        "[Appearance]",
        f"ColorScheme={SCHEME[variant]}",
        "",
        "[Cursor Options]",
        f"CustomCursorColor={rgb(t['cursor-background-color'])}",
        f"CustomCursorTextColor={rgb(t['cursor-foreground-color'])}",
        "UseCustomCursorColor=true",
        "",
        "[General]",
        f"Name={NAME[variant]}",
        "Parent=FALLBACK/",
        "",
    ])


# --- KSyntaxHighlighting (Kate) ------------------------------------------------

def syntax_theme(variant):
    p, _ = colors(variant)

    def style(color, **flags):
        d = {"text-color": p[color], "selected-text-color": p[color]}
        d.update({k.replace("_", "-"): v for k, v in flags.items()})
        return d

    # Four syntax colors, as in the other editor schemes: fuchsia for
    # keywords and what the preprocessor sees, purple for values and types,
    # yellow for strings, muted italic for comments; ink for the rest.
    text_styles = {
        "Normal": style("ink"),
        "Keyword": style("pink"),
        "ControlFlow": style("pink"),
        "Preprocessor": style("pink"),
        "Import": style("pink"),
        "Attribute": style("pink"),
        "Function": style("ink"),
        "Operator": style("ink"),
        "Others": style("ink"),
        "Variable": style("purple"),
        "BuiltIn": style("purple"),
        "Extension": style("purple"),
        "DataType": style("purple"),
        "DecVal": style("purple"),
        "BaseN": style("purple"),
        "Float": style("purple"),
        "Constant": style("purple"),
        "SpecialChar": style("purple"),
        "Char": style("string"),
        "String": style("string"),
        "VerbatimString": style("string"),
        "SpecialString": style("string"),
        "Comment": style("muted", italic=True),
        "Documentation": style("muted", italic=True),
        "RegionMarker": style("muted"),
        "Annotation": style("purple", italic=True),
        "CommentVar": style("purple", italic=True),
        "Information": style("string", italic=True),
        "Warning": style("string"),
        "Alert": {**style("pink"), "background-color": p["wash-pink"]},
        "Error": style("del", underline=True),
    }
    editor = {
        "BackgroundColor": "bg",
        "BracketMatching": "wash-pink",
        "CodeFolding": "wash-strong",
        "CurrentLine": "wash",
        "CurrentLineNumber": "pink",
        "IconBorder": "bg",
        "IndentationLine": "line",
        "LineNumbers": "dimmest",
        "MarkBookmark": "purple",
        "MarkBreakpointActive": "del",
        "MarkBreakpointDisabled": "dimmest",
        "MarkBreakpointReached": "string",
        "MarkError": "del",
        "MarkExecution": "pink",
        "MarkWarning": "string",
        "ModifiedLines": "string",
        "ReplaceHighlight": "wash-pink",
        "SavedLines": "add",
        "SearchHighlight": "press",
        "Separator": "edge-purple",
        "SpellChecking": "del",
        "TabMarker": "dimmest",
        "TemplateBackground": "wash",
        "TemplateFocusedPlaceholder": "wash-pink",
        "TemplatePlaceholder": "wash-strong",
        "TemplateReadOnlyPlaceholder": "wash",
        "TextSelection": "select",
        "WordWrapMarker": "line",
    }
    theme = {
        "metadata": {
            "name": NAME[variant],
            "revision": 1,
            "license": "SPDX-License-Identifier: " + LICENSE,
            "copyright": [f"SPDX-FileCopyrightText: 2026 {AUTHOR}"],
        },
        "text-styles": text_styles,
        "editor-colors": {k: p[v] for k, v in editor.items()},
        "custom-styles": {},
    }
    return json.dumps(theme, indent=4) + "\n"


# --- qt5ct and qt6ct -----------------------------------------------------------

def qtct(variant):
    p, _ = colors(variant)
    # QPalette's roles, in its order. Qt 6.6 added a 22nd, Accent, but
    # qt6ct's own schemes stop at 21, and so does this, for both.
    roles = {
        "WindowText": p["ink"], "Button": p["wash"], "Light": p["line"],
        "Midlight": p["line"], "Dark": p["bg"], "Mid": p["line"], "Text": p["ink"],
        "BrightText": p["pink"], "ButtonText": p["ink"], "Base": p["bg"],
        "Window": p["bg"], "Shadow": p["bg"], "Highlight": p["select"],
        "HighlightedText": p["ink"], "Link": p["purple"], "LinkVisited": p["purple"],
        "AlternateBase": p["wash"], "NoRole": p["bg"], "ToolTipBase": p["panel"],
        "ToolTipText": p["ink"], "PlaceholderText": p["dimmest"],
    }
    inactive = roles | {"Highlight": p["press"]}
    disabled = roles | {k: p["dimmest"] for k in ("WindowText", "Text", "ButtonText", "HighlightedText")}

    def row(r):
        return ", ".join(f"#ff{v.lstrip('#')}" for v in r.values())

    return "\n".join([
        "[ColorScheme]",
        f"active_colors={row(roles)}",
        f"disabled_colors={row(disabled)}",
        f"inactive_colors={row(inactive)}",
        "",
    ])


def outputs():
    for v in VARIANTS:
        yield OUT / "color-schemes" / f"{SCHEME[v]}.colors", color_scheme(v)
        yield OUT / "Kvantum" / "NeonDoll" / f"{KVANTUM[v]}.kvconfig", kvantum_config(v)
        yield OUT / "Kvantum" / "NeonDoll" / f"{KVANTUM[v]}.svg", kvantum_svg(v)
        yield from look_and_feel(v)
        yield OUT / "konsole" / f"{SCHEME[v]}.colorscheme", konsole_scheme(v)
        yield OUT / "konsole" / f"{NAME[v]}.profile", konsole_profile(v)
        yield OUT / "syntax-highlighting" / f"neon-doll-{v}.theme", syntax_theme(v)
        yield OUT / "qtct" / f"{SCHEME[v]}.conf", qtct(v)


def main():
    check = "--check" in sys.argv
    stale = []
    for path, text in outputs():
        data = text.encode()
        if check:
            if not path.exists() or path.read_bytes() != data:
                stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
            print(path.relative_to(ROOT))
    if stale:
        sys.exit("stale: " + ", ".join(map(str, stale)) + " (run tools/build-kde.py)")


main()
