#!/usr/bin/env python3
"""Build the COSMIC themes and COSMIC Terminal schemes.

    tools/build-cosmic.py            write cosmic/
    tools/build-cosmic.py --check    fail if the output is stale

cosmic/Neon-Doll-{Dark,Light}.ron are COSMIC theme builders, the format
Settings → Appearance exports and imports, and what

    cosmic-settings appearance import cosmic/Neon-Doll-Dark.ron

applies. A builder holds a few seed colors, and COSMIC derives every surface
and state from them, so this sets the seeds: the page, the panel as the
container, ink as the text tint, a plum grey as the control tint, and purple
as the accent, which COSMIC spends on everything you can touch, focus
included. Fuchsia has one place to go: the window hint, the outline on the
focused window, which is where you are. Corners are square, and nothing is
frosted.

cosmic/terminal/ holds COSMIC Terminal's schemes, the Tilix colors entry for
entry. The terminal imports them itself, from its Settings.
"""

import json
import sys
from pathlib import Path

import tokens

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "cosmic"

# COSMIC's own swatches, for the accent picker's colors Neon Doll has no
# token for. Settings shows palette.accent_* as the row of accent choices.
COSMIC_DEFAULTS = {
    "dark": {
        "accent_indigo": "#A1C0EB", "accent_orange": "#FFAD00", "accent_warm_grey": "#CABAB4",
        "ext_warm_grey": "#9B8E8A", "ext_orange": "#FFAD00", "ext_yellow": "#FEDB40",
        "ext_blue": "#48B9C7", "ext_purple": "#CF7DFF", "ext_pink": "#F93A83", "ext_indigo": "#3E88FF",
    },
    "light": {
        "accent_indigo": "#2E496D", "accent_orange": "#624000", "accent_warm_grey": "#554742",
        "ext_warm_grey": "#9B8E8A", "ext_orange": "#FBB86C", "ext_yellow": "#F7E062",
        "ext_blue": "#6ACAD8", "ext_purple": "#D58CFF", "ext_pink": "#FF9CDD", "ext_indigo": "#95C4FC",
    },
}

ANSI = ("black", "red", "green", "yellow", "blue", "magenta", "cyan", "white")


def c(h, alpha="FF"):
    return f'"{h.lstrip("#").upper().join(("#", alpha))}"'


def tilix(variant):
    return json.loads((ROOT / "tilix" / f"neon-doll-{variant}.json").read_text())


def palette(variant):
    """COSMIC's palette: the page ramp, and the accent swatches.

    neutral_0 to neutral_10 run from the page to the ink in both variants, as
    COSMIC's own do (black to white in dark, white to black in light), so
    every derived grey is a plum one."""
    p, ansi = tokens.palette(variant), tilix(variant)["palette"]
    colors = {
        "bright_red": p["diff-del"],
        "bright_green": p["diff-add"],
        "bright_orange": p["code-string"],
        "gray_1": p["bg"],
        "gray_2": p["panel"],
    }
    colors |= {f"neutral_{i}": tokens.over(p["bg"], p["ink"], i / 10) for i in range(11)}
    colors |= {
        "accent_blue": ansi[4],
        "accent_purple": p["purple"],
        "accent_pink": p["pink"],
        "accent_red": p["diff-del"],
        "accent_yellow": p["code-string"],
        "accent_green": p["diff-add"],
    }
    colors |= COSMIC_DEFAULTS[variant]
    order = ["bright_red", "bright_green", "bright_orange", "gray_1", "gray_2",
             *(f"neutral_{i}" for i in range(11)),
             "accent_blue", "accent_indigo", "accent_purple", "accent_pink", "accent_red",
             "accent_orange", "accent_yellow", "accent_green", "accent_warm_grey",
             "ext_warm_grey", "ext_orange", "ext_yellow", "ext_blue", "ext_purple", "ext_pink",
             "ext_indigo"]
    body = "".join(f"        {k}: {c(colors[k])},\n" for k in order)
    return f'{variant.title()}((\n        name: "neon-doll-{variant}",\n{body}    ))'


def theme(variant):
    p = tokens.palette(variant)
    square = "(0.0, 0.0, 0.0, 0.0)"
    radii = "".join(f"        radius_{r}: {square},\n" for r in ("0", "xs", "s", "m", "l", "xl"))
    return f"""\
// Neon Doll {variant.title()}, for COSMIC. Generated by tools/build-cosmic.py; edit that, not this.
// Apply with: cosmic-settings appearance import Neon-Doll-{variant.title()}.ron
(
    palette: {palette(variant)},
    spacing: (
        space_none: 0,
        space_xxxs: 4,
        space_xxs: 8,
        space_xs: 12,
        space_s: 16,
        space_m: 24,
        space_l: 32,
        space_xl: 48,
        space_xxl: 64,
        space_xxxl: 128,
    ),
    corner_radii: (
{radii}    ),
    neutral_tint: Some({c(p["dimmest"])}),
    bg_color: Some({c(p["bg"])}),
    primary_container_bg: Some({c(p["panel"])}),
    secondary_container_bg: None,
    text_tint: Some({c(p["ink"])}),
    accent: Some({c(p["purple"])}),
    success: Some({c(p["diff-add"])}),
    warning: Some({c(p["code-string"])}),
    destructive: Some({c(p["diff-del"])}),
    frosted: Medium,
    gaps: (0, 8),
    active_hint: 2,
    window_hint: Some({c(p["pink"])}),
    frosted_windows: false,
    frosted_system_interface: false,
    frosted_panel: false,
    frosted_applets: false,
    frosted_maximized_apps: false,
)
"""


def terminal(variant):
    t, p = tilix(variant), tokens.palette(variant)
    ansi = t["palette"]

    def block(name, colors):
        rows = "".join(f'        {n}: "{h}",\n' for n, h in zip(ANSI, colors))
        return f"    {name}: (\n{rows}    ),\n"

    # No header comment: COSMIC Terminal keeps imported schemes in its config,
    # which won't parse with one.
    return (
        "(\n"
        f'    name: "Neon Doll {variant.title()}",\n'
        f'    foreground: "{t["foreground-color"]}",\n'
        f'    background: "{t["background-color"]}",\n'
        f'    cursor: "{t["cursor-background-color"]}",\n'
        f'    bright_foreground: "{p["ink"]}",\n'
        f'    dim_foreground: "{p["muted"]}",\n'
        + block("normal", ansi[:8])
        + block("bright", ansi[8:])
        + block("dim", [tokens.over(t["background-color"], h, 0.7) for h in ansi[:8]])
        + ")\n"
    )


def outputs():
    for variant in tokens.VARIANTS:
        yield OUT / f"Neon-Doll-{variant.title()}.ron", theme(variant).encode()
        yield OUT / "terminal" / f"Neon Doll {variant.title()}.ron", terminal(variant).encode()


def main():
    check = "--check" in sys.argv
    stale = []
    for path, data in outputs():
        if check:
            if not path.exists() or path.read_bytes() != data:
                stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
            print(path.relative_to(ROOT))
    if stale:
        sys.exit("stale: " + ", ".join(map(str, stale)) + " (run tools/build-cosmic.py)")


main()
