#!/usr/bin/env python3
"""Build the Ghostty themes from the Tilix schemes.

    tools/build-ghostty.py            write ghostty/themes/
    tools/build-ghostty.py --check    fail if the output is stale

Two theme files, "Neon Doll Dark" and "Neon Doll Light", with the Tilix
schemes' colors entry for entry. Ghostty can switch between them with the
system style on its own:

    theme = light:Neon Doll Light,dark:Neon Doll Dark

Beyond the palette, a Ghostty theme can set any option, so these also carry
the parts Tilix has no key for: the split divider in the border color,
unfocused splits fading toward the page rather than grey, and search results.
Matches are purple, the one you're on is fuchsia, since that's where you are.

Ghostty's own window is GTK 4 and libadwaita, so its tabs and header bar take
Neon Doll from gtk-4.0/gtk.css.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "ghostty" / "themes"

PURPLE = {"dark": "#b48cff", "light": "#6a3fd0"}


def theme(variant):
    t = json.loads((ROOT / "tilix" / f"neon-doll-{variant}.json").read_text())
    bg, fg = t["background-color"], t["foreground-color"]
    pink = t["cursor-background-color"]
    line = t["palette"][0]
    lines = [
        f"# Neon Doll {variant.title()}. Generated by tools/build-ghostty.py; edit that, not this.",
        f"background = {bg}",
        f"foreground = {fg}",
        f"cursor-color = {pink}",
        f"cursor-text = {bg}",
        f"selection-background = {t['highlight-background-color']}",
        f"selection-foreground = {t['highlight-foreground-color']}",
    ]
    lines += [f"palette = {i}={c}" for i, c in enumerate(t["palette"])]
    lines += [
        f"split-divider-color = {line}",
        f"unfocused-split-fill = {bg}",
        f"search-background = {PURPLE[variant]}",
        f"search-foreground = {bg}",
        f"search-selected-background = {pink}",
        f"search-selected-foreground = {bg}",
    ]
    return "\n".join(lines) + "\n"


def outputs():
    for variant in ("dark", "light"):
        yield OUT / f"Neon Doll {variant.title()}", theme(variant).encode()


def main():
    check = "--check" in sys.argv
    stale = []
    for path, data in outputs():
        if check:
            if not path.exists() or path.read_bytes() != data:
                stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
            print(path.relative_to(ROOT))
    if stale:
        sys.exit("stale: " + ", ".join(map(str, stale)) + " (run tools/build-ghostty.py)")


main()
