#!/usr/bin/env python3
"""Build the Roundcube skin into roundcube/neon-doll/.

The skin is a child of Elastic, Roundcube's default: it keeps Elastic's
templates, icons and scripts, and its stylesheet is Elastic's LESS compiled
with Neon Doll's colors and rules on top. Output is committed, so installing
is a copy.

    tools/build-roundcube.py                  write the palette and the CSS
    tools/build-roundcube.py --check          fail if either is stale
    tools/build-roundcube.py --elastic DIR    compile against this Elastic
                                              (skins/elastic in a Roundcube
                                              checkout or release)

Written from tokens.toml: styles/_palette.less (every color as a CSS custom
property, light on :root and dark on html.dark-mode, which is the class
Roundcube's own light/dark switch toggles) and watermark.html (the empty
preview pane, as graph paper). Compiled: styles/{styles,embed,print}.css,
from the hand-written styles/*.less. Copied: templates/includes/layout.html,
Elastic's own, unchanged. It is the template that links the stylesheet, and
Roundcube 1.6 resolves the paths in an included template from the skin the
include was found in first; left to Elastic's copy, the link finds
Elastic's styles.css wherever that exists (Debian's package builds one) and
never reaches ours.

Compiling needs Elastic's LESS sources and lessc. Without --elastic, Elastic
is fetched at the pinned release into ~/.cache/neon-doll; lessc is the
pinned one through npx, else the one on PATH. If either can't be had, the
CSS is left alone (and --check skips it) with a warning, so tools/build.sh
still runs offline.
"""

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import tokens

ROOT = Path(__file__).resolve().parent.parent
SKIN = ROOT / "roundcube" / "neon-doll"
ELASTIC_TAG = "1.7.4"
ELASTIC_REPO = "https://github.com/roundcube/roundcubemail.git"
CACHE = Path(os.environ.get("XDG_CACHE_HOME", Path.home() / ".cache")) / "neon-doll"
LESS = "less@4.9.1"

CORE = ("bg", "panel", "line", "ink", "muted", "dimmest", "pink", "purple",
        "code-string", "diff-add", "diff-del")
# The two quote levels past purple, from the terminal colors.
ANSI = {"cyan": "6 cyan", "blue": "4 blue"}


def props(variant):
    p = tokens.palette(variant)
    f = tokens.flat(variant)
    ansi = {name: c for name, c, _ in f["ansi"]}
    out = [f"--nd-{k}: {p[k]};" for k in CORE]
    out += [f"--nd-{k}: {ansi[v]};" for k, v in ANSI.items()]
    out += [f"--nd-{t}: {tokens.css(variant, t)};" for t in tokens.tints(variant)]
    # A tint laid flat on the panel, for the few places Elastic stacks one
    # translucent layer on another and the two would add up.
    out.append(f"--nd-panel-wash: {tokens.over(p['panel'], *tokens.tint(variant, 'wash'))};")
    return out


def palette_less():
    light, dark = props("light"), props("dark")
    lines = [
        "// Generated by tools/build-roundcube.py from tokens.toml. Don't edit.",
        "//",
        "// Every color is a custom property, so one set of rules serves both",
        "// variants: light on :root, dark on html.dark-mode, the class",
        "// Roundcube's own light/dark switch sets.",
        "",
        ":root {",
        "    color-scheme: light;",
        *("    " + l for l in light),
        "}",
        "",
        "html.dark-mode {",
        "    color-scheme: dark;",
        *("    " + l for l in dark),
        "}",
        "",
        "// Paper is light, whatever the screen is: a printout, and an HTML",
        "// message, which Roundcube shows on white in dark mode too, since",
        "// its sender chose its colors for white.",
        "@media print {",
        "    html.dark-mode {",
        "        color-scheme: light;",
        *("        " + l for l in light),
        "    }",
        "}",
        "",
        "html.dark-mode .message-htmlpart {",
        "    color-scheme: light;",
        *("    " + l for l in light),
        "}",
        "",
        "// As LESS colors too, for the SVG drawn into a data: URL, which can't",
        "// see a custom property.",
        *(f"@nd-{v}-{k}: {tokens.palette(v)[k]};" for v in tokens.VARIANTS for k in CORE),
        "",
    ]
    return "\n".join(lines)


def watermark():
    """The empty content pane: graph paper, as where a window shows through."""
    def rules(v):
        grid = tokens.css(v, "grid")
        bg = tokens.palette(v)["bg"]
        return (f"background-color: {bg};\n"
                f"  background-image: linear-gradient({grid} 1px, transparent 1px),\n"
                f"    linear-gradient(90deg, {grid} 1px, transparent 1px);")
    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title></title>
<!-- Generated by tools/build-roundcube.py from tokens.toml. Don't edit. -->
<style>
html, body {{ height: 100%; margin: 0; overflow: hidden; }}
body {{
  {rules("light")}
  background-size: 24px 24px;
}}
html.dark-mode > body {{
  {rules("dark")}
}}
</style>
<script>
  try {{
    if (document.cookie.indexOf('colorMode=dark') > -1
      || (document.cookie.indexOf('colorMode=light') === -1 && window.matchMedia('(prefers-color-scheme: dark)').matches)
    ) {{
      document.documentElement.className += ' dark-mode';
    }}
  }} catch (e) {{ }}
</script>
</head>
<body></body>
</html>
"""


# --- compiling ------------------------------------------------------------------

def elastic(arg):
    if arg:
        path = Path(arg).resolve()
        if not (path / "styles" / "styles.less").exists():
            sys.exit(f"{path}: no styles/styles.less; want skins/elastic from Roundcube {ELASTIC_TAG}")
        return path
    checkout = CACHE / f"roundcube-{ELASTIC_TAG}"
    path = checkout / "skins" / "elastic"
    if (path / "styles" / "styles.less").exists():
        return path
    CACHE.mkdir(parents=True, exist_ok=True)
    shutil.rmtree(checkout, ignore_errors=True)
    try:
        subprocess.run(["git", "clone", "-q", "--depth", "1", "--branch", ELASTIC_TAG,
                        "--filter=blob:none", "--sparse", ELASTIC_REPO, str(checkout)],
                       check=True, stderr=subprocess.DEVNULL, timeout=300)
        subprocess.run(["git", "-C", str(checkout), "sparse-checkout", "set", "skins/elastic"],
                       check=True, stderr=subprocess.DEVNULL, timeout=300)
    except (OSError, subprocess.SubprocessError):
        shutil.rmtree(checkout, ignore_errors=True)
        return None
    return path


def lessc():
    # The pinned one first: another lessc can write the same CSS differently,
    # and --check would call it stale.
    if shutil.which("npx"):
        return ["npx", "--yes", f"--package={LESS}", "lessc"]
    if shutil.which("lessc"):
        return ["lessc"]
    return None


def compile_css(elastic_dir, less):
    """{name: css} for the three stylesheets Roundcube loads from a skin."""
    with tempfile.TemporaryDirectory() as tmp:
        # Laid out as they are installed, side by side under skins/, so the
        # rewritten font and image URLs point from ours into Elastic's.
        skins = Path(tmp) / "skins"
        skins.mkdir()
        (skins / "elastic").symlink_to(elastic_dir)
        shutil.copytree(SKIN / "styles", skins / "neon-doll" / "styles",
                        ignore=shutil.ignore_patterns("*.css"))
        out = {}
        for name in ("styles", "embed", "print"):
            r = subprocess.run(less + ["--rewrite-urls=all", "--include-path=styles", f"styles/{name}.less"],
                               cwd=skins / "neon-doll", capture_output=True, text=True)
            if r.returncode:
                sys.exit(f"lessc {name}.less:\n{r.stderr}")
            out[name] = ("/* Generated by tools/build-roundcube.py from roundcube/neon-doll/styles/"
                         f"{name}.less\n   and Roundcube {ELASTIC_TAG}'s Elastic skin. Don't edit.\n"
                         "   Licensed CC BY-SA 4.0; see README.md. */\n"
                         + r.stdout)
        return out


def layout(elastic_dir):
    return (elastic_dir / "templates" / "includes" / "layout.html").read_text()


def main():
    args = sys.argv[1:]
    check = "--check" in args
    elastic_arg = args[args.index("--elastic") + 1] if "--elastic" in args else None

    outputs = {
        SKIN / "styles" / "_palette.less": palette_less(),
        SKIN / "watermark.html": watermark(),
    }
    # The palette goes down first: the CSS is compiled from it.
    if not check:
        for path, text in outputs.items():
            path.write_text(text)

    edir, less = elastic(elastic_arg), lessc()
    if edir and less:
        for name, css in compile_css(edir, less).items():
            outputs[SKIN / "styles" / f"{name}.css"] = css
        outputs[SKIN / "templates" / "includes" / "layout.html"] = layout(edir)
    else:
        why = "no Elastic sources" if not edir else "no lessc or npx"
        print(f"warning: {why}; CSS not {'checked' if check else 'rebuilt'}", file=sys.stderr)

    stale = []
    for path, text in outputs.items():
        if check:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(path.relative_to(ROOT))
    if stale:
        sys.exit("stale: " + ", ".join(stale) + " (run tools/build-roundcube.py)")


main()
