#!/usr/bin/env python3
"""Build the GTK 2 part of the theme dirs from tokens.toml.

    tools/build-gtk2.py            write themes/Neon-Doll-{Dark,Light}/gtk-2.0/gtkrc
    tools/build-gtk2.py --check    fail if either is stale

A few apps are still GTK 2 (HexChat, GIMP 2, older tools), and GNOME's theme
setting reaches them too: without a gtk-2.0 dir in the theme they fall back
to GTK 2's bare default, grey bevels and all. Drawing every GTK 2 widget
again is not worth it this late, so this borrows Adwaita's GTK 2 theme (from
gnome-themes-extra), which takes all its colors from one gtk-color-scheme
block, and gives it Neon Doll's: the page and panel, ink and muted, purple
links, and the selection in the flattened pink tint, as in the editors.
Adwaita's own images (check boxes, scroll bars, buttons) stay as they are.
"""

import sys
from pathlib import Path

import tokens

ROOT = Path(__file__).resolve().parent.parent
ADWAITA = {"dark": "/usr/share/themes/Adwaita-dark/gtk-2.0",
           "light": "/usr/share/themes/Adwaita/gtk-2.0"}


def gtkrc(variant):
    f = tokens.flat(variant)
    scheme = [
        ("text_color", f["ink"]), ("base_color", f["bg"]),
        ("fg_color", f["ink"]), ("bg_color", f["bg"]),
        ("selected_fg_color", f["ink"]), ("selected_bg_color", f["select"]),
        ("insensitive_fg_color", f["dimmest"]), ("insensitive_bg_color", f["bg"]),
        ("menu_color", f["panel"]),
        ("link_color", f["purple"]), ("visited_link_color", f["purple"]),
        ("column_header_color", f["muted"]), ("hover_column_header_color", f["ink"]),
        ("window_color", f["panel"]),
        ("tooltip_fg_color", f["ink"]), ("tooltip_bg_color", f["panel"]),
    ]
    adwaita = ADWAITA[variant]
    lines = [
        f"# Neon Doll {variant.title()} for GTK 2: Adwaita's GTK 2 widgets in Neon Doll's colors.",
        "# Generated by tools/build-gtk2.py from tokens.toml; edit those, not this.",
        "# Needs Adwaita's GTK 2 theme (gnome-themes-extra).",
        "",
    ]
    lines += [f'gtk-color-scheme = "{k}:{v}"' for k, v in scheme]
    lines += [
        "",
        "gtk-auto-mnemonics              = 1",
        "gtk-primary-button-warps-slider = 1",
        "",
        f'include "{adwaita}/main.rc"',
        f'include "{adwaita}/apps.rc"',
        f'include "{adwaita}/hacks.rc"',
    ]
    if variant == "dark":
        lines.append(f'include "{adwaita}/hacks-dark.rc"')
    return "\n".join(lines) + "\n"


def outputs():
    for v in tokens.VARIANTS:
        yield ROOT / "themes" / f"Neon-Doll-{v.title()}" / "gtk-2.0" / "gtkrc", gtkrc(v)


def main():
    check = "--check" in sys.argv
    stale = []
    for path, text in outputs():
        if check:
            if not path.exists() or path.read_text() != text:
                stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(path.relative_to(ROOT))
    if stale:
        sys.exit("stale: " + ", ".join(map(str, stale)) + " (run tools/build-gtk2.py)")


main()
