#!/usr/bin/env python3
"""Derive the Neon Doll text-scheme colors and report their contrast.

The colors come from tokens.toml, flattened onto the page by tools/tokens.py
(see flat() there for the rules); this reports their contrast and writes the
schemes that take them.

    tools/scheme-colors.py            # report both variants
    tools/scheme-colors.py dark       # report one variant
    tools/scheme-colors.py --write    # regenerate gtksourceview/ and tilix/
    tools/scheme-colors.py --check    # fail if they are stale

The Emacs palettes, flattened the same way, are written into the theme files
by tools/build-palettes.py, since those files have to stand alone.
"""
import json
import os
import sys

from tokens import contrast, over
from tokens import flat as derive


def report(name):
    p = derive(name)
    bg = p["bg"]
    print("== %s ==" % name)
    print("Flattened tints over --bg %s" % bg)
    for k in ("wash", "wash-strong", "grid", "press", "select", "wash-pink",
              "ul-purple", "add-bg", "del-bg", "add-bg-hl", "del-bg-hl",
              "add-refine", "del-refine", "change-bg"):
        print("  %-12s %s" % (k, p[k]))

    print("\nText on --bg / on the current-line wash %s" % p["wash"])
    for k in ("ink", "pink", "string", "muted", "purple", "dimmest", "add", "del"):
        print("  %-8s %s  %5.2f  %5.2f" % (k, p[k], contrast(p[k], bg), contrast(p[k], p["wash"])))

    print("\nOn tinted rows")
    for label, fg, b in [
        ("ink on selection", "ink", "select"), ("pink on selection", "pink", "select"),
        ("ink on press", "ink", "press"), ("pink on wash-pink", "pink", "wash-pink"),
        ("add on add-bg", "add", "add-bg"), ("del on del-bg", "del", "del-bg"),
        ("string on change-bg", "string", "change-bg"),
        ("bright green on add-bg-hl", "bright-green", "add-bg-hl"),
        ("bright red on del-bg-hl", "bright-red", "del-bg-hl"),
        ("ink on add-refine", "ink", "add-refine"),
        ("ink on del-refine", "ink", "del-refine"),
        ("bg on pink", "bg", "pink"), ("pink on panel", "pink", "panel"),
        ("ink on panel", "ink", "panel"), ("muted on panel", "muted", "panel"),
    ]:
        print("  %-26s %5.2f" % (label, contrast(p[fg], p[b])))

    print("\nANSI palette, contrast on --bg %s" % bg)
    for label, c, how in p["ansi"]:
        r = contrast(c, bg)
        flag = "" if r >= 4.5 or label.startswith("0 ") else "   < 4.5"
        print("  %-18s %s  %5.2f:1  %s%s" % (label, c, r, how, flag))
    print("  %-18s %s  %5.2f:1  --pink, not in the sixteen"
          % ("cursor", p["pink"], contrast(p["pink"], bg)))
    print()


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Colors named in the GtkSourceView scheme, in this order.
GSV_COLORS = ("bg", "panel", "line", "ink", "muted", "dimmest", "pink", "purple",
              "string", "add", "del", "wash", "wash-strong", "grid", "press",
              "select", "wash-pink", "edge-purple", "add-bg", "del-bg",
              "change-bg")

GSV_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<!--
  Neon Doll {Title}: a GtkSourceView style scheme (GNOME Text Editor, gedit,
  Builder and anything else built on GtkSourceView).

  Copyright (C) 2026 Misha Nasledov <misha@nasledov.com>
  SPDX-License-Identifier: GPL-3.0-or-later
  This scheme is free software under the GNU General Public License, version 3
  or (at your option) any later version. It comes with NO WARRANTY. See COPYING.

  Generated by tools/scheme-colors.py; edit that, not this.

  The editor is the page, so the text area is bg rather than the site's
  code-block field; that field (wash) becomes the current line instead.

  Four syntax colors and no more. Every extra class folds onto one of them:
    pink    keywords, statements, preprocessor, tags, attributes and macros
    purple  numbers, constants, booleans, types, builtins, escapes,
            variables with a sigil ($var), link text
    string  strings and characters
    muted   comments (italic), doc comments, shebangs
    ink     identifiers, functions, operators: everything else
  Fuchsia is also position: the cursor, the current line number, the matching
  bracket and the selection (which is where the search match under the cursor
  lands). Purple is the resting state: other search matches, the secondary
  cursor, links. Diff rows carry both a text color and a full-width tint.
-->
<style-scheme id="neon-doll-{variant}" name="Neon Doll {Title}" version="1.0">
  <author>Misha Nasledov</author>
  <description>{description}</description>
  <metadata>
    <property name="variant">{variant}</property>
    <property name="{other}-variant">neon-doll-{other}</property>
  </metadata>

{colors}

  <!-- Global -->
  <style name="text"                  foreground="ink" background="bg"/>
  <style name="selection"             foreground="ink" background="select"/>
  <style name="selection-unfocused"   foreground="ink" background="press"/>
  <style name="cursor"                foreground="pink"/>
  <style name="secondary-cursor"      foreground="purple"/>
  <style name="current-line"          background="wash"/>
  <style name="line-numbers"          foreground="dimmest" background="bg"/>
  <style name="current-line-number"   foreground="pink" background="wash"/>
  <style name="line-numbers-border"   background="edge-purple"/>
  <style name="right-margin"          foreground="line" background="line"/>
  <style name="draw-spaces"           foreground="dimmest"/>
  <style name="background-pattern"    background="grid"/>
  <style name="bracket-match"         foreground="pink" background="wash-pink"/>
  <style name="bracket-mismatch"      foreground="del" background="del-bg" underline="single"/>
  <style name="search-match"          foreground="ink" background="press"/>
  <style name="snippet-focus"         background="wash-pink"/>
  <style name="map-overlay"           background="{map_overlay}"/>

  <!-- Comments -->
  <style name="def:comment"              foreground="muted" italic="true"/>
  <style name="def:shebang"              foreground="muted" italic="true"/>
  <style name="def:doc-comment"          foreground="muted" italic="true"/>
  <style name="def:doc-comment-element"  foreground="purple" italic="true"/>

  <!-- Constants -->
  <style name="def:constant"             foreground="purple"/>
  <style name="def:special-constant"     foreground="purple"/>
  <style name="def:boolean"              foreground="purple"/>
  <style name="def:number"               foreground="purple"/>
  <style name="def:decimal"              foreground="purple"/>
  <style name="def:base-n-integer"       foreground="purple"/>
  <style name="def:floating-point"       foreground="purple"/>
  <style name="def:complex"              foreground="purple"/>
  <style name="def:character"            foreground="string"/>
  <style name="def:string"               foreground="string"/>
  <style name="def:special-char"         foreground="purple"/>

  <!-- Code -->
  <style name="def:keyword"              foreground="pink"/>
  <style name="def:statement"            foreground="pink"/>
  <style name="def:preprocessor"         foreground="pink"/>
  <style name="def:type"                 foreground="purple"/>
  <style name="def:identifier"           foreground="ink"/>
  <style name="def:function"             foreground="ink"/>
  <style name="def:builtin"              foreground="purple"/>
  <style name="def:operator"             foreground="ink"/>

  <!-- Diagnostics -->
  <style name="def:error"                underline="error" underline-color="del"/>
  <style name="def:warning"              underline="error" underline-color="string"/>
  <style name="def:note"                 foreground="string" italic="true"/>
  <style name="def:underlined"           underline="single"/>

  <!-- Markup. Headings are mono and weight 400, as on the site. -->
  <style name="def:heading"              foreground="ink"/>
  <style name="def:emphasis"             italic="true"/>
  <style name="def:strong-emphasis"      bold="true"/>
  <style name="def:inline-code"          foreground="ink" background="wash-strong"/>
  <style name="def:preformatted-section" foreground="ink" background="wash"/>
  <style name="def:list-marker"          foreground="muted"/>
  <style name="def:thematic-break"       foreground="muted"/>
  <style name="def:link-text"            foreground="purple"/>
  <style name="def:link-symbol"          foreground="muted"/>
  <style name="def:link-destination"     foreground="muted" underline="single"/>
  <style name="def:net-address"          foreground="purple" underline="single"/>
  <style name="def:insertion"            foreground="add"/>
  <style name="def:deletion"             foreground="del" strikethrough="true"/>

  <!-- Diff: text color and a full-width row tint, and the +/- stays. -->
  <style name="diff:added-line"          foreground="add" line-background="add-bg"/>
  <style name="diff:removed-line"        foreground="del" line-background="del-bg"/>
  <style name="diff:changed-line"        foreground="string" line-background="change-bg"/>
  <style name="diff:location"            foreground="purple"/>
  <style name="diff:diff-file"           foreground="muted"/>
  <style name="diff:special-case"        foreground="muted"/>

  <!-- A variable with a sigil is purple, as $slot is on the site. -->
  <style name="php:variable"             foreground="purple"/>
  <style name="sh:variable"              foreground="purple"/>
  <style name="perl:variable"            foreground="purple"/>
  <style name="ruby:instance-variable"   foreground="purple"/>

  <!-- Markup tags are keywords; attributes are keys. -->
  <style name="xml:element-name"         foreground="pink"/>
  <style name="xml:attribute-name"       foreground="purple"/>
  <style name="xml:attribute-value"      foreground="string"/>
  <style name="xml:namespace"            foreground="purple"/>
  <style name="xml:processing-instruction" foreground="pink"/>
  <style name="css:property-name"        foreground="purple"/>
  <style name="css:vendor-specific"      foreground="purple"/>

  <!-- Language odds and ends, folded onto the four. -->
  <style name="c:printf"                 foreground="purple"/>
  <style name="rust:macro"               foreground="pink"/>
  <style name="rust:attribute"           foreground="pink"/>
  <style name="rust:lifetime"            foreground="purple"/>
  <style name="python:decorator"         foreground="pink"/>
  <style name="json:keyname"             foreground="purple"/>
</style-scheme>
"""


def gsv(variant):
    p = derive(variant)
    other = "light" if variant == "dark" else "dark"
    colors = "\n".join('  <color name="%s"%s value="%s"/>'
                       % (k, " " * (12 - len(k)), p[k]) for k in GSV_COLORS)
    desc = ("A dark plum page, fuchsia for position, purple for the rest."
            if variant == "dark" else
            "Plum-tinted paper, fuchsia for position, purple for the rest.")
    # Text Editor drops the alpha on the map slider, so it gets the tint
    # already composited over the page.
    return GSV_TEMPLATE.format(Title=variant.title(), variant=variant, other=other,
                               description=desc, colors=colors,
                               map_overlay=over(p["bg"], p["pink"], 0.10))


def gsv4(variant):
    """GtkSourceView 4 (gedit, older apps) rejects the whole file on an
    unknown <metadata> node, so its copy goes without; nothing else differs."""
    text = gsv(variant)
    start, end = text.index("  <metadata>"), text.index("</metadata>\n") + len("</metadata>\n")
    return text[:start] + text[end:]


def tilix(variant):
    p = derive(variant)
    return json.dumps({
        "name": "Neon Doll %s" % variant.title(),
        "comment": "Fuchsia is the cursor and nothing else",
        "use-theme-colors": False,
        "foreground-color": p["ink"],
        "background-color": p["bg"],
        "use-cursor-color": True,
        "cursor-background-color": p["pink"],
        "cursor-foreground-color": p["bg"],
        "use-highlight-color": True,
        "highlight-background-color": p["select"],
        "highlight-foreground-color": p["ink"],
        "use-badge-color": True,
        "badge-color": p["muted"],
        "use-bold-color": True,
        "bold-color": p["ink"],
        "palette": [c for _, c, _ in p["ansi"]],
    }, indent=4) + "\n"


def write(path, text):
    full = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w") as f:
        f.write(text)
    print("wrote", path)


def outputs():
    for v in ("dark", "light"):
        yield "gtksourceview/neon-doll-%s.xml" % v, gsv(v)
        yield "gtksourceview/gtksourceview-4/neon-doll-%s.xml" % v, gsv4(v)
        yield "tilix/neon-doll-%s.json" % v, tilix(v)


if __name__ == "__main__":
    args = sys.argv[1:]
    if args == ["--write"]:
        for path, text in outputs():
            write(path, text)
    elif args == ["--check"]:
        stale = []
        for path, text in outputs():
            with open(os.path.join(ROOT, path)) as f:
                if f.read() != text:
                    stale.append(path)
        if stale:
            sys.exit("stale: " + ", ".join(stale) + " (run tools/scheme-colors.py --write)")
    else:
        for n in args or ("dark", "light"):
            report(n)
