# Neon Doll Light, a Konsole profile. Generated by tools/build-kde.py; edit that, not this.
# A color scheme can't set the cursor color; a profile can.

[Appearance]
ColorScheme=NeonDollLight

[Cursor Options]
CustomCursorColor=200,0,106
CustomCursorTextColor=247,244,250
UseCustomCursorColor=true

[General]
Name=Neon Doll Light
Parent=FALLBACK/
