# Neon Doll Dark, a Konsole profile. Generated by tools/build-kde.py; edit that, not this.
# A color scheme can't set the cursor color; a profile can.

[Appearance]
ColorScheme=NeonDollDark

[Cursor Options]
CustomCursorColor=255,45,149
CustomCursorTextColor=15,13,20
UseCustomCursorColor=true

[General]
Name=Neon Doll Dark
Parent=FALLBACK/
